### PR TITLE
Proposal for hook system in RTCSession

### PR DESCRIPTION
**Pull request by voidpp**
I need a solution to process the whole request in some special cases, so an event is not suitable for me, because I need to alter the request before it's sent out.

This proposed hook system do the job.
It's kinda basic implementation, but it's expandable.

What do you think about it?

### CODE REVIEW

**Comment by hthetiot** [comment]
I think EventEmmiter pattern would be more elegant than hooks like this, personnaly.

**Comment by ibc** [comment]
Why doesn't an event work for you? The event may happen before the packet is sent so you can modify it.

**Comment by voidpp** [comment]
Wait, EventEmitter's emit() is not async? So it's guaranteed all the event handlers will be called before we move on?

I assumed the opposite... (obviously)

**Comment by ibc** [comment]
> EventEmitter's emit() is not async?

It's 100% sync.

**Comment by voidpp** [comment]
Holy cow.

**Pull request closed without merging**
