### PR TITLE
Emit SDP before new RTCSessionDescription

### PR DESCRIPTION
**Pull request by StarLeafRob**
Emit SDP before creating a new RTCSessionDescription. Ensures the user is able to modify it.

Just a tweak to ensure this is done everywhere in RTCSession.js.

### CODE REVIEW

**Comment by ibc** [comment]
@jmillan may you please take a look to this?

**Comment by jmillan** [comment]
Thanks @StarLeafRob and sorry for the delay.

Would you be so kind to add an entry to the [CLI](http://jssip.net/contribute/)?

**Comment by StarLeafRob** [comment]
No worries, glad to help!

**Comment by jmillan** [comment]
Thanks @StarLeafRob!

 New version is already out.

**Comment by jmillan** [comment]
Something didn't work on the merge. Let me check it.

**Comment by jmillan** [comment]
3.0.10.

**Pull request merged**
