### PR TITLE
Fixed parsing `rport` in `Via` header (#642).

### LINKED ISSUE #642: Via header parser doesn't parse rport
Parsing `Via` header doesn't parse `rport`.  To reproduce, just add `rport` to the test case:

```javascript
'parse Via' : function(test)
  {
    const data = 'SIP /  3.0 \r\n / UDP [1:ab::FF]:6060 ;\r\n  BRanch=1234;rport=12345;Param1=Foo;paRAM2;param3=Bar';
    const via = JsSIP.Grammar.parse(data, 'Via');

    test.strictEqual(via.protocol, 'SIP');
    test.strictEqual(via.transport, 'UDP');
    test.strictEqual(via.host, '[1:ab::FF]');
    test.strictEqual(via.host_type, 'IPv6');
    test.strictEqual(via.port, 6060);
    test.strictEqual(via.branch, '1234');
    test.strictEqual(via.rport, 12345);
    test.deepEqual(via.params, { param1: 'Foo', param2: undefined, param3: 'Bar' });

    test.done();
  },
```

The test is failing.

### PR DESCRIPTION
**Pull request by artemtam**
Fixes #642.

### CODE REVIEW

**Comment by jmillan** [comment]
Some description is needed along with the source code in a PR. The current issue, the motivation, etc.

The changes in the PR are not spec compliant.

**Comment by jmillan** [comment]
#642

**Comment by ibc** [comment]
AFAIR rport value is optional. This PR makes is mandatory which is against the spec.

**Comment by artemtam** [comment]
@jmillan the reference issue is in the PR title
@ibc I am not familiar with PegJs syntax; however, there is a check for undefined and tests are passing without `rport` – it seems everything works fine.

**Comment by ibc** [comment]
I mean that rport can have no value, not that rport key is mandatory. Please ensure your PR honors ABNF grammar in RFC 3261.

**Comment by jmillan** [comment]
> @jmillan the reference issue is in the PR title

Right, I did not realise.

**Comment by jmillan** [comment]
already fixed in new vesion.

**Pull request closed without merging**
