### PR TITLE
Use a proper Logger class

### PR DESCRIPTION
**Pull request by jmillan**

### CODE REVIEW

**Comment by lamuertepeluda** [comment]
Hi @jmillan is this the PR that should also help solve #713?

I tried the new Logger class. It looks ok, but I cannot understand how to enable the whole logs or the selected namespaces...

Perhaps adding a static method like this?

```javascript
const debug = require('debug');

const APP_NAME = 'JsSIP';

module.exports = class Logger
{

  static enable(namespaces) { debug.enable(namespaces); }

  constructor(prefix)
  {
    if (prefix)
    {
      this._debug = debug.default(`${APP_NAME}:${prefix}`);
      this._warn = debug.default(`${APP_NAME}:WARN:${prefix}`);
      this._error = debug.default(`${APP_NAME}:ERROR:${prefix}`);
    }
    else
    {
      this._debug = debug.default(APP_NAME);
      this._warn = debug.default(`${APP_NAME}:WARN`);
      this._error = debug.default(`${APP_NAME}:ERROR`);
    }
    /* eslint-disable no-console */
    this._debug.log = console.info.bind(console);
    this._warn.log = console.warn.bind(console);
    this._error.log = console.error.bind(console);
    /* eslint-enable no-console */
  }

  get debug()
  {
    return this._debug;
  }

  get warn()
  {
    return this._warn;
  }

  get error()
  {
    return this._error;
  }
};
```

I tried it and it seems to work. Here is my Node REPL output

```bash
❯ node
Welcome to Node.js v14.15.4.
Type ".help" for more information.
> var Logger = require('./lib/Logger')
undefined
> var l = new Logger('something')
undefined
> var l2 = new Logger('something ELSE')
undefined
> l2.debug('hey there')
undefined
> l.debug('hello')
undefined
> Logger.enable('JsSIP:*')   # <-- the missing method
undefined
> l.debug('hello again')
  JsSIP:something hello again +0ms
undefined
> l2.debug('hey there again')
  JsSIP:something ELSE hey there again +0ms
undefined
```

**Comment by lamuertepeluda** [comment]
Actually you should also provide a `disable` static method, i.e.

```javascript
class Logger
{

  /**
   * Enable namespaces debug
   * @param {string[]} [namespaces] optional
   */
  static enable(namespaces) { debug.enable(namespaces); }

...
  /**
   * Disable debug
   */
  static disable() { debug.disable(); }
  ```

**Comment by lamuertepeluda** [comment]
@jmillan I was still looking at your class implementation and it still wouldn't solve my issue (#713 ), but with a small change like this it would:

```javascript
const debug = require('debug');

const APP_NAME = 'JsSIP';

/* eslint-disable no-console */
let defaultDebugLog = console.info.bind(console);
let defaultWarnLog = console.warn.bind(console);
let defaultErrorLog = console.error.bind(console);
/* eslint-enable no-console */


module.exports = class Logger
{

  /**
   * Static setter for debug logger
   * @param {(...any:[]) => void} loggerFn 
   */
  static setDefaultDebugLog(loggerFn) { defaultDebugLog = loggerFn; }

  /**
   * Static setter for warn logger
   * @param {(...any:[]) => void} loggerFn 
   */
  static setDefaultWarnLog(loggerFn) { defaultWarnLog = loggerFn; }

  /**
   * Static setter for error logger
   * @param {(...any:[]) => void} loggerFn 
   */
  static setDefaultErrorLog(loggerFn) { defaultErrorLog = loggerFn; }

  /**
   * Enable namespaces
   * @param {string[]} [namespaces] optional
   */
  static enable(namespaces) { debug.enable(namespaces); }

  /**
   * Disable debug
   */
  static disable() { debug.disable(); }

  constructor(prefix)
  {
    if (prefix)
    {
      this._debug = debug.default(`${APP_NAME}:${prefix}`);
      this._warn = debug.default(`${APP_NAME}:WARN:${prefix}`);
      this._error = debug.default(`${APP_NAME}:ERROR:${prefix}`);
    }
    else
    {
      this._debug = debug.default(APP_NAME);
      this._warn = debug.default(`${APP_NAME}:WARN`);
      this._error = debug.default(`${APP_NAME}:ERROR`);
    }

    this._debug.log = (...args) => defaultDebugLog(...args);
    this._warn.log = (...args) => defaultWarnLog(...args);
    this._error.log = (...args) => defaultErrorLog(...args);

  }

  get debug()
  {
    return this._debug;
  }

  get warn()
  {
    return this._warn;
  }

  get error()
  {
    return this._error;
  }
};
```

Basically I defined some module-level private variables for the loggers (since I didn't find any way to set a static private property without TypeScript, apart from ES2020 provate props which are rejected by the linter rules and could break older environments), and I set some static getters for the Logger class.

Check the example below

image

The example is of course trivial, but it would be easy to add some interceptors for log messages, like e.g. sending to a backend using services such as track.js or azure application insights.

**Comment by jmillan** [comment]
@lamuertepeluda

This is a previous PR to your request. It will require some additions after merging.

**Comment by lamuertepeluda** [comment]
@jmillan yeah, I thought so. Mine are just suggestions since I was finding a way to solve the problem that I reported in the issue.

If it's OK for you this way, feel free to grab stuff from the code above.

**Review by ibc — APPROVED** [review]

**Comment by jmillan** [comment]
Added to new release.

**Pull request closed without merging**
