### PR TITLE
new RTCSession event on('sdp')

### PR DESCRIPTION
**Pull request by jmillan**
Event data attributes:
- originator
- type
- sdp

- originator='remote' is fired before passing a remote SDP to RTCPeerConnection.
- originator='local' is fired before sending a local SDP.

### CODE REVIEW

**Comment by jmillan** [comment]
@ibc, @saghul, comments?

**Comment by saghul** [comment]
LGTM. One question: what need are you covering with this?

**Comment by ibc** [comment]
It looks very nice, but please check [this concern](https://github.com/versatica/JsSIP/commit/853104a7a0cc9d694b0d2d2391fb7eb267168d44#commitcomment-17286080).

@saghul this new event covers all the historical needs requested by so many users regarding the ability of mangling remote SDPs before they are given to the WebRTC stack and local SDPs before they are sent over the network.

**Comment by ibc** [comment]
Hi, any reason for this PR not to be merged yet?

**Comment by jmillan** [comment]
No. I just wanted to update the docs accordingly.

@ibc, did you mean to create 1.0.0 right after this MR, so this would be available on 1.0.0?

**Comment by jmillan** [comment]
> No. I just wanted to update the docs accordingly.

I know it's trivial. I really didn't find the time lately.

**Comment by ibc** [comment]
I propose merging this PR first in master. Once done let's label 1.0.0 and I will update the docs.

**Comment by jmillan** [comment]
Already done

**Pull request closed without merging**
