### PR TITLE
emit data when parse message fails

### PR DESCRIPTION
**Pull request by lazedo**

### CODE REVIEW

**Comment by jmillan** [comment]
Please, explain the rationale of this PR.

**Comment by jmillan** [comment]
wouldn't a log line do the work?

**Comment by lazedo** [comment]
@jmillan Hello, the intent is to handle `non-sip` payloads when using the same socket for sip & json events

**Comment by jmillan** [comment]
@lazedo,

This is why there is a [Socket interface](https://jssip.net/documentation/3.4.x/api/socket/) so you can implement your own socket that handles SIP and no SIP traffic.

If any doubt please ask in the mailing list.

**Pull request closed without merging**
