### PR TITLE
use sdpSemantics: 'plan-b'

### PR DESCRIPTION
**Pull request by Krivega**
to support Chrome 72
fix for sdpSemantics: 'unified-plan' in process

### CODE REVIEW

**Comment by Krivega** [comment]
because in version 72 the default unified-plan is used. and in the current implementation of the library this causes an erro, because it just uses plan b, although not explicitly.r. it's not about personal preference.

**Comment by Krivega** [comment]
see https://webrtc.org/web-apis/chrome/unified-plan/

**Comment by rshpount** [comment]
@Krivega Can you describe what error this causes?

There was an issue with M72 beta, but as far as I know this was fixed.

**Comment by Krivega** [comment]
@rshpount ok, i will reproduce the error and attach the link

**Comment by ibc** [comment]
> because in version 72 the default unified-plan is used. and in the current implementation of the library this causes an error, because it just uses plan b, although not explicitly. it's not about personal preference.

JsSIP does not assume plan-b or unified-plan.

**Pull request closed without merging**
