### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/versatica/JsSIP/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/versatica/JsSIP).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by ibc** [comment]
Well, your stuff helped us identifying a few bugs that were not detected by `eslint`, so thanks :)

**Comment by ibc** [comment]
Just a question: how often is the snapshot updated? I've fixed the alerts given by LGTM but they are still shown.

**Comment by xcorail** [comment]
Hi @ibc 

By default, LGTM polls your repo once a day, and analyzes all new commits, most recent first
But we recommend to activate automated code review. In this case, LGTM will analyze immediately your Pull requests, and report any new problem directly in the comments. It's a [one click operation](https://lgtm.com/projects/g/versatica/JsSIP/ci/)

Cheers

**Comment by ibc** [comment]
Clear, thanks :)

**Comment by jmillan** [comment]
Thanks @xcorail, very nice!

**Pull request merged**
