### PR TITLE
fix: add some check on recovery_options interval

### PR DESCRIPTION
**Pull request by spike008t**
Hello,

Here a PR to check the following options : 
- recovery_option.min_interval
- recovery_option.max_interval

That solve an issue I did encountered. I did have a while loop without any interval when retrying to connect.

### CODE REVIEW

**Comment by jmillan** [comment]
This is a bug within your code, which was providing an incorrect `recovery_options` to JsSIP

**Comment by ibc** [comment]
> This is a bug within your code, which was providing an incorrect `recovery_options` to JsSIP

I agree. We cannot sanitize every wrong input the app may attempt to use.

**Comment by jmillan** [comment]
Anyways is good to do some basic checks. Let me check it.

**Comment by jmillan** [comment]
Yeah, well. Lets close it.

**Pull request closed without merging**
