### PR TITLE
Fix typescript typings

### PR DESCRIPTION
**Pull request by phwb**

### CODE REVIEW

**Comment by phwb** [comment]
@jmillan can you review PR?

**Comment by arkaev** [comment]
Wait. Why not devDependencies?

**Comment by phwb** [comment]
> Wait. Why not devDependencies?

Because some types extends `EventEmitter`

**Comment by IlyaCherkasov** [comment]
Would love this to be merged to fix typings in project

**Comment by IlyaCherkasov** [comment]
Would love this to be merged to fix typings in project

**Review by jmillan — APPROVED** [review]

**Review by ibc — APPROVED** [review]

**Comment by jmillan** [comment]
CHANGELOG was missing

**Comment by jmillan** [comment]
> CHANGELOG was missing

Updated.

**Pull request merged**
