### PR TITLE
Enable echo cancellation and noise suppression

### PR DESCRIPTION
**Pull request by andrey-utkin**
I don't have the reference to source of this solution at hand, but to my knowledge this fixes echo issues in both Chrome and Firefox.

### CODE REVIEW

**Comment by saghul** [comment]
I doubt any goog* prefixed optins have any meaning on Firefox. At any rate, these changes need to go in the real source, not in the generated one in dist/.

**Comment by andrey-utkin** [comment]
I wonder about goog* too, but AFAIK Firefox uses some parts of webrtc implementation with Chrome, no?

**Comment by saghul** [comment]
Yep, they do use the same WebRTC engine but AFAIK they have their own PeerConnection. Some links to documentation / code would help.

**Comment by andrey-utkin** [comment]
The new commit makes it in lib/
Untested, will look at it later (or maybe you guys find time earlier).

**Comment by ibc** [comment]
@andrey-utkin thanks a lot for pointing this trick out, but I'm against hardcoding vendor private stuff in JsSIP, even more when the user can already pass those constraints via the `mediaConstraints` object in both `ua.call()` and `session.answer()` methods. If we added those constraints to JsSIP then we'd have to track them forever, and I do not want such a responsibility.

Thanks a lot.

**Pull request closed without merging**
